name: Build and Deploy Config Server

on:
    push:
        branches:  [ main ]
    pull_request: 
        branches:  [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup .Net environment
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore
              working-directory: ./src/SimpleConfigServer

            - name: Build
              run: dotnet build --no-restore --configuration Release
              working-directory: ./src/SimpleConfigServer

            - name: Test
              run: dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage"
              working-directory: ./src/SimpleConfigServer

            - name: Upload coverage reports
              uses: codecov/codecov-action@v3
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                fail_ci_if_error: true
                flags: unitttests


    build-and-push:
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        strategy:
            matrix:
                platform: [linux/amd64, linux/arm64]
    
        steps:
            - uses: actions/checkout@v3
    
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
    
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
    
            - name: Login to Container Registry
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.REGISTRY_USERNAME }}
                password: ${{ secrets.REGISTRY_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile
                platforms: ${{ matrix.platform }}
                push: true
                tags: |
                    ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/simple-config-server:${{ contains(matrix.platform, 'arm64') && 'arm64' || 'amd64' }}-latest
                    ${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USERNAME }}/simple-config-server:${{ contains(matrix.platform, 'arm64') && 'arm64' || 'amd64' }}-${{ github.sha }}
                              
    create-release:
        needs: build-and-push
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
                        
        steps:
            - uses: actions/checkout@v3
                       
            - name: Create Release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: v${{ github.run_number }}
                release_name: Release v${{ github.run_number }}
                draft: false
                prerelease: false 
            